#! /usr/bin/env bash
session=$(find ~/Coding -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename "$session" | tr . _)

if [ -z "${TMUX}" ]; then
  tmux new-session -s  "$session_name" -d -c "$session"
  tmux a
else 
  if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -s "$session_name" -d -c "$session"
  fi

  tmux switch-client -t "$session_name"
fi
