- hosts: localhost
  become: true
  tasks:
  - name: Install dotfiles
    git:
      repo: https://github.com/jacktrusler/.dotfiles
      dest: ~/.dotfiles
    tags:
      - dotfiles
  - name: Create Folders
    file:
      path: "{{item}}"
      state: directory
    loop:
      - "~/.cache/"
      - "~/Coding/"
    tags:
      - dotfiles
